/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./app/**/*.{js,ts,jsx,tsx}', './components/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#62468d',
        'primary-container': '#7b5ea7',
        'primary-fixed': '#ecdcff',
        'primary-fixed-dim': '#d6baff',
        'inverse-primary': '#d6baff',
        secondary: '#755b00',
        'secondary-container': '#fed977',
        'secondary-fixed': '#ffe08f',
        'secondary-fixed-dim': '#e6c364',
        tertiary: '#5c4c7d',
        'tertiary-container': '#756497',
        surface: '#fcf8ff',
        'surface-dim': '#dad7f3',
        'surface-bright': '#fcf8ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f2ff',
        'surface-container': '#efecff',
        'surface-container-high': '#e8e5ff',
        'surface-container-highest': '#e2e0fc',
        'surface-variant': '#e2e0fc',
        'inverse-surface': '#2f2e43',
        'inverse-on-surface': '#f2efff',
        'on-surface': '#1a1a2e',
        'on-surface-variant': '#4a454f',
        'on-primary': '#ffffff',
        'on-secondary': '#ffffff',
        'on-tertiary': '#ffffff',
        'on-secondary-fixed': '#241a00',
        'on-secondary-fixed-variant': '#584400',
        'on-primary-container': '#f6ebff',
        'on-secondary-container': '#785d00',
        'on-tertiary-container': '#f5ebff',
        'on-primary-fixed': '#270550',
        'on-primary-fixed-variant': '#54387e',
        background: '#fcf8ff',
        'on-background': '#1a1a2e',
        outline: '#7b7581',
        'outline-variant': '#ccc4d1',
        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'brand-gold': '#C9A84C',
        'brand-lavender': '#F3EFFF',
      },
      borderRadius: {
        DEFAULT: '16px',
        sm: '8px',
        lg: '16px',
        xl: '24px',
        full: '9999px',
      },
      fontFamily: {
        poppins: ['Poppins', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
        jakarta: ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      boxShadow: {
        soft: '0 4px 24px rgba(123, 94, 167, 0.08)',
        card: '0 2px 12px rgba(123, 94, 167, 0.12)',
        gold: '0 4px 20px rgba(201, 168, 76, 0.25)',
      },
    },
  },
  plugins: [],
}
